### ISSUE TITLE
`keyHelper` should trim whitespace on `inKey`

### ISSUE THREAD

**Issue by phorward** [viur-framework/viur-datastore#12]
Calling keyHelper with this key
```
    key = agNsb2xyDgsSBHJ1c3QiBGVtaWwM
    project = lol
    namespace = None
    kind = rust
    id = None
    name = emil
    parent = None
    to_path = rust/emil
```
this way
```python
db.keyHelper("agNsb2xyDgsSBHJ1c3QiBGVtaWwM", "rust", ["python"])
```
and this way
```python
db.keyHelper(" agNsb2xyDgsSBHJ1c3QiBGVtaWwM", "rust", ["python"])
```
returns entirely different results. In latter case, the key cannot be parsed, and produces a new key with the old key as name.

To fix it, just strip the inKey in the str-case!

**Comment by XeoN-GHMB** [comment]
Take a look at: https://github.com/viur-framework/viur-datastore/pull/13

**Comment by skoegl** [comment]
Hey, I don't think modifying given input is the right way. Let it crash when invalid key representations are been given.

**Comment by phorward** [comment]
> Hey, I don't think modifying given input is the right way. Let it crash when invalid key representations are been given.

The problem is: It doesn't crash, it generates keys with broken/invalid content. Please try it on your own. This issue is not solved!

**Comment by phorward** [comment]
Hmm... I've now tested it again, and the problem I've initially recognized is not reproduceable. I don't know why. Therefore I'm closing this case for now.

**Comment by skoegl** [comment]
> The problem is: It doesn't crash, it generates keys with broken/invalid content. Please try it on your own. This issue is not solved!

Ok, let me paraphrase it. Guessing and modifying input is error shadowing. We are transforming a key representation into an internal object. If the input is wrong, the consumer made a mistake and this is not a bug in viur-datastore!
