### ISSUE TITLE
Use Semantic Versioning scheme

### ISSUE THREAD

**Issue by sveneberth** [viur-framework/viur-datastore#2]
Can we please use the de facto standard scheme [_Semantic Versioning_](https://semver.org/) (MAJOR.MINOR.PATCH) for versions of viur-datastore?

**Comment by tsteinruecken** [comment]
Responsibility for this project has been transferred to sk, he'd have to decide on this.

**Comment by skoegl** [comment]
We will apply the semver version scheme starting from the next release.

**Comment by skoegl** [comment]
Accepted and closed by now
