### ISSUE TITLE
Improve logging output on missing index

### ISSUE THREAD

**Issue by phorward** [viur-framework/viur-datastore#4]
Hello!

When an index is missing, viur-datastore fails with an "INVALID STATUS CODE" message and returns the exception content as text. 

This looks like this in the logging:
```
INVALID STATUS CODE RECEIVED
b'{\n  "error": {\n    "code": 400,\n    "message": "no matching index found. recommended index is:\\n- kind: optionrule\\n  properties:\\n  - name: channel.dest.__key__\\n  - name: kind\\n  - name: sortindex\\n",\n    "status": "FAILED_PRECONDITION"\n  }\n}\n'
{'error': {'code': 400,
           'message': 'no matching index found. recommended index is:\n'
                      '- kind: optionrule\n'
                      '  properties:\n'
                      '  - name: channel.dest.__key__\n'
                      '  - name: kind\n'
                      '  - name: sortindex\n',
           'status': 'FAILED_PRECONDITION'}}
ERROR:root:Viur caught an unhandled exception!
ERROR    2022-05-02 14:48:42,943 request.py:283] Viur caught an unhandled exception!
```
It's okay, but not very user-friendly to copy the recommended index definition from this log into the index.yaml of the project. Can this be improved?

**Comment by tsteinruecken** [comment]
We currently provide some viur-sepecific classes (like Skeleton) to the datastore-wrapper.
What if we also provide a way, to override the exceptions it throws? This way, we could indicate a temporary error (like 503 Service Unavailable) if an index is in building state to the user?
